### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ulrischa** [potibm/phluesky#17]
How can I install it? There are only PSRs in the require section.

**Comment by potibm** [comment]
This depends a little on the framework you are using. I am using Symfony where the DI is doing all the magic to create the `HttpComponentsManager`. 

I will send a sample using `symfony/http-client`(in require-dev) later the evening.

**Comment by ulrischa** [comment]
Thank you very much

**Comment by potibm** [comment]
Sorry for my incomplete answer from earlier the day. 

In your project you have to require one of the clients (or an adapters) from https://docs.php-http.org/en/latest/clients.html. For testing and development I use `symfony/http-client` -- which is in the required-dev.

The rest is done automatically (using the `php-http/discovery` package), so you instantiate 

`$api = new BlueskyApi('nick.bsky.social', 'abcd-efgh-ijkl-mnop');`

like it says in the README.md and start posting to Bluesky.

**Comment by ulrischa** [comment]
Thanks

**Comment by potibm** [comment]
@ulrischa could you take a look at #19? Thanks!
