### ISSUE TITLE
Can I specify one URL and use PHP to retrieve only one bluesky post by someone else?

### ISSUE THREAD

**Issue by e1blue** [potibm/phluesky#20]
I want to retrieve someone else's specific post. if I am using Bluesky and happen to find a post I like, can I use PHP to retrieve that one post? I want to embed it in my blog and display it.

**Comment by martinburch** [comment]
You might want to use a more generic oEmbed PHP library like https://github.com/ricardofiorani/oembed which can support any oEmbed endpoint, including Bluesky.

https://embed.bsky.app/oembed?url=https://bsky.app/profile/mkarolian.bsky.social/post/3lbunm54agc2k

**Comment by potibm** [comment]
Sorry @e1blue, but this is probably beyond the scope of the library...
