### ISSUE TITLE
When posting a POST to Bluesky, if there is a URL in the text body, how do I link to that URL?　*This is not a link card.

### ISSUE THREAD

**Issue by e1blue** [potibm/phluesky#22]
When posting a POST to Bluesky, if there is a URL in the text body, how do I link to that URL?　*This is not a link card.

**Comment by potibm** [comment]
Have you tried https://github.com/potibm/phluesky#adding-mentions-and-links-from-post-text? `addFacetsFromMentionsAndLinks` does exactly that...

**Comment by e1blue** [comment]
Thank you for your response & presenting the link.
It was very helpful.
