### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by rknightuk** [potibm/phluesky#24]
Hi, I've been using this library in my project but needed to add support for tags by extending this library. 

Would you be happy for a pull request to add this? Happy to put one up if you do.

**Comment by potibm** [comment]
Hey Robb. Nice to hear that the library is of any use for you :) I would be more than happy to review a merge request once you provide one. But I might also find some time to add this feature myself...

**Comment by rknightuk** [comment]
Pull request opened here: https://github.com/potibm/phluesky/pull/25
