### ISSUE TITLE
How do I get a URI from the createRecord response?

### ISSUE THREAD

**Issue by martinburch** [potibm/phluesky#33]
phluesky creates the Bluesky post correctly, but how do I learn the location?

```
$post = \potibm\Bluesky\Feed\Post::create($my_text);
$response = $api->createRecord($post);
var_dump($response->getUri()->parts);
```

Causes this error

> Fatal error: Uncaught Error: Cannot access private property potibm\Bluesky\BlueskyUri::$parts

I don't see anything public returned by the getUri() method.

EDIT: As a terrible workaround, I can do

```
$property = new ReflectionProperty('potibm\Bluesky\BlueskyUri', 'parts');
$property->setAccessible(true);
var_dump($property->getValue($response->getUri())[2]);
```

**Comment by potibm** [comment]
Sorry for not taking care, first of all. Will take a look...

**Comment by potibm** [comment]
@martinburch could you elaborate on this? in my understanding it should be pretty straightforward:

```php
$record = $api->createRecord($post);
$uri = $record->getUri();

var_dump($uri->getUri());
var_dump($uri->getDID());
var_dump($uri->getNSID());
var_dump($uri->getRecord());
```
